apiVersion: v1
kind: Service
metadata:
  name: quantumtrust-backend
  namespace: quantumtrust
  labels:
    app: quantumtrust-backend
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: quantumtrust-backend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quantumtrust-backend-ingress
  namespace: quantumtrust
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "quantumtrust-ip"
    networking.gke.io/managed-certificates: "quantumtrust-certificate"
    networking.gke.io/v1beta1.FrontendConfig: "quantumtrust-frontend-config"
spec:
  rules:
  - host: api.quantumtrust.example.com
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: quantumtrust-backend
            port:
              number: 8000
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: quantumtrust-frontend-config
  namespace: quantumtrust
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
